### ISSUE TITLE
CSV Parser

### ISSUE THREAD

**Issue by canerbagci** [jmueller95/Network-Analysis-Tool#2]

**Comment by canerbagci** [comment]
- [ ] Two types of CSV files: ReadName2TaxID TaxID2Count

- [ ] Return a sample object, or a list of samples

- [ ] Sample object can contain a Map object of Taxon to Count (you can make taxon an integer for now (taxId) but once we have the tree it should link to the nodes of the tree)

**Comment by jmueller95** [comment]
- [ ] Test CSV Parser using JUnit  (@NantiaL)

**Comment by canerbagci** [comment]
@NantiaL @jmueller95 
Hi Nantia, Julian,
The reason test case returned a NullPointerException during the class is not because of a bug in your code, but because of how HashMap works in Java.
First of all, we used random values for name and rank etc. They should be initialized as null at this point as we don't have the tree. And the second reason was you can't get them from HashMap this way, because HashMap works with equals and hashcode methods which we haven't overwritten at this point. So, I'd suggest:

- a) wait for Tree is fixed and Julian can actually return real taxonNode objects, which in test cases can also be retrieved from the tree and then HashMap should work and not return null, actually.
- b) overwrite hashcode and equals methods in TaxonNode class in such a way that, two TaxonNode objects will be seen as equal if they have the same id, name, rank etc. (but I think this is only a temporary solution).
