### ISSUE TITLE
NCBI Taxdump Parser

### ISSUE THREAD

**Issue by canerbagci** [jmueller95/Network-Analysis-Tool#3]

**Comment by canerbagci** [comment]
- [ ] get taxdump from [ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/](ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/)

- [ ] parse nodes.dmp and names.dmp

- [ ] return a tree structure

- [ ] tree can contain a map of taxId to taxonNode

**Comment by Zethson** [comment]
The files are too large to upload on Github.

Should I upload them in a res folder like in the following?
https://git-lfs.github.com

**Comment by canerbagci** [comment]
@Zethson 

Then no need to push them. Git LFS has a bandwith quota of 1GB per month. If all of us pull them, we'll already exceed it.

**Comment by Zethson** [comment]
I see, good to know. But how should we get the files then? I thought that we would provide them in the res folder, because they are required for building the tree. The user shouldn't have to provide those two files to my mind.
Or will we simply just not push them?

**Comment by canerbagci** [comment]
We can think of this in future. But simply we can have an install script, which will download, extract and place them in the correct folder.
Right now we don't even have a main class yet. When we start building up one, we will discuss where and how to store those files by default.

**Comment by Zethson** [comment]
All right, thanks!

**Comment by jmueller95** [comment]
So I just committed a resources folder - can you all put your 'names.dmp' and 'nodes.dmp' files right into that folder (without adding them to git)? That way, we can all use the same filepath for them without actually having them up in the repository.
