### ISSUE TITLE
Project setup in IntelliJ working for you?

### ISSUE THREAD

**Issue by caspargross** [jmueller95/Network-Analysis-Tool#4]
Hey everyone!
Are you able to pull/push and run the (test) application? 
@jmueller95 
for me it worked fine without the .iml file you provided. This is the one i use:

**Comment by caspargross** [comment]
[Network-Analysis-Tool.txt](https://github.com/jmueller95/Network-Analysis-Tool/files/1011112/Network-Analysis-Tool.txt)

had to change file extension

**Comment by jmueller95** [comment]
The test works for me! 
Ok, I can take the iml file down again, I guess something was wrong in my IDE.

**Comment by KaikiasVind** [comment]
Working

**Comment by Zethson** [comment]
Yup.

Suggestion of mine: since five people will be working on the project I suggest that we should settle on some coding conventions. Else this will become messy pretty soon ;)
