### ISSUE TITLE
Start building the basic parts of GUI

### ISSUE THREAD

**Issue by canerbagci** [jmueller95/Network-Analysis-Tool#6]
- [x] Start a main class

- [x] Have tree loaded when the tool starts

- [x] Look into FXML and Scene Builder

- [x] continue building a basic GUI

- [x] fix saveAndQuit

- [x] fix fileNotFound triggering when closing Alert

- [x] fix optionsFXML loader

- [x] load samples -> multiple files

- [x] loading files -> dropdown menu and user chooses file format

- [x] change bottom left and bottom right status to something useful

- [x] put analysis into tab pane

- [x] add some useful stuff to the options scene

- [x] beautify the GUI

- [x] preload files using concurrent programming (service class)

- [ ] bind progressbar and tasks progress

**Comment by Zethson** [comment]
Which Scene Builder are we gonna use? The gluon scene builder?

**Comment by canerbagci** [comment]
IntelliJ supports Oracle Scene Builder 2. I'd suggest that.
https://www.jetbrains.com/help/idea/2017.1/opening-fxml-files-in-javafx-scene-builder.html

**Comment by Zethson** [comment]
All right, seems like gluon is also maintaining this one now. Oracle did not provide installers for their own scene builder for a long time.

https://www.quora.com/Is-Gluons-Scene-Builder-the-same-as-the-Oracle-JavaFX-Scene-Builder

**Comment by canerbagci** [comment]
If you are more comfortable with that or think it is better, fine for me.

**Comment by canerbagci** [comment]
some of the tasks here are redundant with Network Visualization. That's fine, but just make sure you communicate and don't implement the same functionality in two different places. :)

**Comment by Zethson** [comment]
Noticed that as well ;)

We have a discord chat for communication, maybe I'll update the list again and remove the redundant things.

**Comment by canerbagci** [comment]
alright, everything seems to be on track. :)
