### ISSUE TITLE
Network Structure

### ISSUE THREAD

**Issue by canerbagci** [jmueller95/Network-Analysis-Tool#7]
We need to implement a) our own graph structure b) find a new library that suits our needs.

Please either implement a basic network or find a library and test it.

We should be able to,

- add attributes to nodes and edges

- hide / show nodes and edges

**Comment by jmueller95** [comment]
I just included the JGraphT library into our project and started doing some tests with it. Do you think it suits our needs? I haven't found customizable Vertex/Edge classes yet (Nodes are called Vertices there), but we could easily implement these by ourselves.
